import Header from "@/components/header";
import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import "./globals.css";

// const jakira = Plus_Jakarta_Sans({
//   variable: "--font-jakira-sans",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`  antialiased`}>
        {children}

        <Header />
        <Toaster />
      </body>
    </html>
  );
}
